from __future__ import annotations

import argparse
import csv
from pathlib import Path


def _maybe_init_swanlab(args: argparse.Namespace):
    if not args.use_swanlab:
        return None

    try:
        import swanlab
    except ImportError as exc:
        raise ImportError(
            "SwanLab is not installed in the current environment. "
            "Install it with `pip install swanlab` or rerun without --use-swanlab."
        ) from exc

    run = swanlab.init(
        project=args.swanlab_project,
        experiment_name=args.swanlab_experiment or args.name,
        config={
            "data": str(args.data),
            "weights": str(args.weights),
            "imgsz": args.imgsz,
            "epochs": args.epochs,
            "batch": args.batch,
            "device": args.device,
            "workers": args.workers,
            "project": args.project,
            "name": args.name,
            "lr0": args.lr0,
            "patience": args.patience,
        },
    )
    return run


def _log_yolo_csv_to_swanlab(save_dir: Path) -> None:
    import swanlab

    results_csv = save_dir / "results.csv"
    if not results_csv.exists():
        print(f"SwanLab sync skipped because {results_csv} was not found.")
        return

    with results_csv.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            payload = {}
            for key, value in row.items():
                key = key.strip()
                if value is None:
                    continue
                value = value.strip()
                if not value:
                    continue
                try:
                    payload[key] = float(value)
                except ValueError:
                    payload[key] = value
            if payload:
                swanlab.log(payload)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Fine-tune a YOLO detector on the local VisDrone dataset."
    )
    parser.add_argument(
        "--data",
        type=Path,
        default=Path("datasets/visdrone_yolo/visdrone_local.yaml"),
        help="YOLO dataset yaml generated by convert_visdrone_to_yolo.py.",
    )
    parser.add_argument(
        "--weights",
        type=Path,
        default=Path("yolov8n.pt"),
        help="Initial checkpoint. Defaults to the official YOLOv8n pretrained weights.",
    )
    parser.add_argument("--imgsz", type=int, default=960)
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--batch", type=int, default=8)
    parser.add_argument("--device", type=str, default="0")
    parser.add_argument("--workers", type=int, default=8)
    parser.add_argument("--project", type=str, default="runs/task2_detect")
    parser.add_argument("--name", type=str, default="visdrone_yolov8n")
    parser.add_argument("--lr0", type=float, default=0.001)
    parser.add_argument("--patience", type=int, default=20)
    parser.add_argument(
        "--use-swanlab",
        action="store_true",
        help="Log training hyperparameters and YOLO results.csv metrics to SwanLab.",
    )
    parser.add_argument(
        "--swanlab-project",
        type=str,
        default="cv-hw2-task2",
        help="SwanLab project name used when --use-swanlab is enabled.",
    )
    parser.add_argument(
        "--swanlab-experiment",
        type=str,
        default="",
        help="Optional SwanLab experiment name. Defaults to --name.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume the latest interrupted training run with the same project/name.",
    )
    parser.add_argument(
        "--exist-ok",
        action="store_true",
        help="Reuse an existing Ultralytics run directory instead of auto-incrementing its name.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    swanlab_run = _maybe_init_swanlab(args)

    from ultralytics import YOLO

    model = YOLO(str(args.weights))
    model.train(
        data=str(args.data),
        imgsz=args.imgsz,
        epochs=args.epochs,
        batch=args.batch,
        device=args.device,
        workers=args.workers,
        project=args.project,
        name=args.name,
        lr0=args.lr0,
        patience=args.patience,
        resume=args.resume,
        exist_ok=args.exist_ok,
        pretrained=True,
        cache=False,
        plots=True,
    )

    if swanlab_run is not None:
        save_dir = Path(model.trainer.save_dir)
        _log_yolo_csv_to_swanlab(save_dir)
        try:
            import swanlab

            swanlab.finish()
        except Exception:
            pass


if __name__ == "__main__":
    main()
